language: scala
env:
  global:
    - SAUCE_USERNAME=overviewproject
    - secure: JcgP+YZaAEsoA1NfKogsAUu/4FSIS1mSmMH0uy6sRk/bFR3F2/IOX2VSPy4LG/lUl+xBSXCItdQARPJXIIOXJ5PBVoCiNHtsMV9aeIwrPr0/gRdVamZ385CdP9bqTSNpZHs8VKLnjFPsSmgzYBY3LsKHnc+sJ3RJhyxX2KrP9uU=
branches:
  only:
  - master
  - /^deploy.*$/
before_install:
  - sudo apt-get update -qq
  - ./auto/setup-coffee-tests.sh
  - ./auto/setup-integration-tests.sh
install:
  - sudo apt-get install -qq postgresql openjdk-7-jdk
before_script:
  # Suppress excessive output from SauceConnect. Assume it works; there are way too many messages otherwise.
  - curl -L https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash > /dev/null
  # Suppress excessive output from Sbt (resolving / downloading). Either it works or it doesn't; all errors are the same to us.
  # Add "show version" calls so Travis sees output; otherwise, if we exceed 10min Travis will bail.
  # Put message-broker near the end: it seems to make Travis exceed 10min sometimes, but it may share dependencies with the others.
  - ./sbt '; set every logLevel := Level.Warn; common/update; show version; worker-common/update; show version; overview-server/update; show version; documentset-worker/update; show version; worker/update; show version; runner/update; show version; db-evolution-applier/update; show version; message-broker/update; show version; search-index/update;'
script:
  - ./auto/test-coffee-once.sh
  - ./run --only-servers database --sbt '; overview-server/test; common/test; worker-common/test; worker/test; documentset-worker/test; runner/test'
  - ./run --sbt '; eval Thread.sleep(120000); eval if (("auto/test-integration.sh"!) != 0) { throw new Exception("integration tests failed") }'
notifications:
  irc:
    - irc.freenode.net#overviewproject
