language: scala
env:
  global:
    - SAUCE_USERNAME=overviewproject
    - secure: JcgP+YZaAEsoA1NfKogsAUu/4FSIS1mSmMH0uy6sRk/bFR3F2/IOX2VSPy4LG/lUl+xBSXCItdQARPJXIIOXJ5PBVoCiNHtsMV9aeIwrPr0/gRdVamZ385CdP9bqTSNpZHs8VKLnjFPsSmgzYBY3LsKHnc+sJ3RJhyxX2KrP9uU=
branches:
  only:
  - master
  - /^deploy.*$/
install:
  - time sudo add-apt-repository ppa:libreoffice/ppa -y
  - time sudo apt-get update -qq
  - time ./auto/setup-coffee-tests.sh
  - time ./auto/setup-integration-tests.sh
  - time sudo apt-get install -qq postgresql openjdk-7-jdk libreoffice
before_script:
  # Suppress excessive output from SauceConnect. Assume it works; there are way too many messages otherwise.
  - curl -L https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash > /dev/null
  # Suppress excessive output from Sbt (resolving / downloading). Either it
  # works or it doesn't; all errors are the same to us.
  #
  # We cache with Artifactory. Configure repos here: http://repo-proxy.overviewproject.org.
  # Any repo that's in Build.scala, plugins.sbt or default sbt needs to be in
  # there for Travis to build. Any repo that _isn't_ should be _gone_, because
  # that will make cache misses much faster.
  #
  # Set the cache expiry times for hits _and_ misses far into the future. Ivy
  # generates N-1 misses for every 1 hit, where N is the total number of
  # repositories.
  #
  # TODO: turn off Artifactory and enable caching on Travis. First we need
  # Travis to support it for our repository. They've told us they're working
  # on it.
  - time ./sbt -Dsbt.log.noformat=true -Dsbt.override.build.repos=true -Dsbt.repository.config=./travis/sbt-repositories '; set every logLevel := Level.Warn; common/update; common-test/update; overview-server/update; documentset-worker/update; worker/update; runner/update; db-evolution-applier/update; search-index/update; message-broker/update'
script:
  # CoffeeScript tests are the fastest, so we put them first
  - time ./auto/test-coffee-once.sh
  # Unit tests next.
  # We need the database to run for the duration of the test commands. So we run --only-servers search-index: we need at least one server running to make the database run.
  - time ./dev --only-servers search-index --sbt '; overview-server/test; common/test; worker/test; documentset-worker/test; runner/test'
  # The build must succeed
  - time SBT_OPTIONS="-Dsbt.override.build.repos=true -Dsbt.repository.config=./travis/sbt-repositories" ./build overview-server.zip
  # Now that we've built, we can run integration tests with the resulting jars
  - time (cd dist && ./run -Doverview-server.props.overview.multi_user=true -Dworker.jvm.Xmx200M= -Ddocumentset-worker.jvm.Xmx200M= -Dsearchindex.jvm.Xmx200M= -Dmessage-broker.jvm.Xmx200M= -Doverview-server.jvm.Xmx200M= --sh ../travis/wait-and-test-integration.sh)
notifications:
  irc:
    - irc.freenode.net#overviewproject
