language: scala
env:
  global:
    - SAUCE_USERNAME=overviewproject
    - secure: JcgP+YZaAEsoA1NfKogsAUu/4FSIS1mSmMH0uy6sRk/bFR3F2/IOX2VSPy4LG/lUl+xBSXCItdQARPJXIIOXJ5PBVoCiNHtsMV9aeIwrPr0/gRdVamZ385CdP9bqTSNpZHs8VKLnjFPsSmgzYBY3LsKHnc+sJ3RJhyxX2KrP9uU=
branches:
  only:
  - master
  - /^deploy.*$/
before_install:
  - sudo apt-get update -qq
  - ./auto/setup-coffee-tests.sh
  - ./auto/setup-integration-tests.sh
install:
  - sudo apt-get install -qq postgresql openjdk-7-jdk
before_script:
  # Suppress excessive output from SauceConnect. Assume it works; there are way too many messages otherwise.
  - curl -L https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash > /dev/null
  # Suppress excessive output from Sbt (resolving / downloading). Either it works or it doesn't; all errors are the same to us.
  # Add "show version" calls so Travis sees output; otherwise, if we exceed 10min Travis will bail.
  # Put message-broker at the end, and log more for it: it seems to make Travis exceed 10min sometimes.
  - ./sbt '; set every logLevel := Level.Warn; common/update; show version; worker-common/update; show version; overview-server/update; show version; documentset-worker/update; show version; worker/update; show version; runner/update; show version; db-evolution-applier/update; search-index/update; show version; set every logLevel := Level.Info; message-broker/update'
script:
  # CoffeeScript tests are the fastest, so we put them first
  - ./auto/test-coffee-once.sh
  # Unit tests next.
  # We need the database to run for the duration of the test commands. So we run --only-servers search-index: we need at least one server running to make the database run.
  - ./dev --only-servers search-index --sbt '; overview-server/test; common/test; worker-common/test; worker/test; documentset-worker/test; runner/test'
  # The build must succeed
  - ./build overview-server.zip
  # Now that we've built, we can run integration tests with the resulting jars
  - ./run --sh auto/wait-and-test-integration.sh
notifications:
  irc:
    - irc.freenode.net#overviewproject
