language: scala
branches:
  only:
    - master
    - /^deploy.*$/
before_install:
  - sudo apt-get update -qq
  - ./auto/setup-grunt.sh
  - ./auto/setup-integration-tests.sh
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
install:
  - sudo apt-get install -qq postgresql openjdk-7-jdk
script:
  - ./auto/test-coffee-once.sh
  - ./run --only-servers database --sbt '; message-broker/update; search-index/update; overview-server/test; common/test; worker-common/test; worker/test; documentset-worker/test; runner/test'
  - ./run --sbt '; eval Thread.sleep(60000); eval if (("auto/test-integration.sh"!) != 0) { throw new Exception("integration tests failed") }'
notifications:
  irc:
    - "irc.freenode.net#overviewproject"
